// apps/web/src/app/[orgShortCode]/convo/new/editor.tsx
'use client';

import {
  EditorRoot,
  EditorCommand,
  // EditorCommandItem,
  EditorCommandEmpty,
  EditorContent,
  type JSONContent
  // EditorCommandList,
  // EditorBubble
} from '@u22n/tiptap/react/components';
import { ScrollArea } from '@radix-ui/themes';
import {
  type Editor as EditorType,
  useCurrentEditor
} from '@u22n/tiptap/react';

interface EditorProp {
  initialValue?: JSONContent;
  onChange: (value: JSONContent) => void;
  setEditor: (editor: EditorType) => void;
}

const Editor = ({ initialValue, onChange, setEditor }: EditorProp) => {
  return (
    <ScrollArea className="border-gray-7 dark:border-graydark-7 rounded-md border">
      <EditorRoot>
        <EditorContent
          className="h-full w-full p-2"
          {...(initialValue && { initialContent: initialValue })}
          editorProps={{
            attributes: {
              class: `prose dark:prose-invert focus:outline-none max-w-full dark:text-white text-black prose-p:my-0 prose-a:decoration-blue-9`
            }
          }}
          onUpdate={({ editor }) => {
            onChange(editor.getJSON());
          }}>
          <EditorCommand className="border-gray-10 dark:border-graydark-10 bg-background z-50 h-auto max-h-[330px] overflow-y-auto rounded-md border px-1 py-2 shadow-md transition-all">
            <EditorCommandEmpty className="px-2">No results</EditorCommandEmpty>
          </EditorCommand>
          <EditorForwarder setEditor={setEditor} />
        </EditorContent>
      </EditorRoot>
    </ScrollArea>
  );
};

function EditorForwarder({
  setEditor
}: {
  setEditor: (editor: EditorType) => void;
}) {
  const { editor } = useCurrentEditor();
  if (editor) setEditor(editor);
  return null;
}

export default Editor;

// apps/web-app/components/un/editor.vue
<script setup lang="ts">
  import { tiptapVue3 } from '@u22n/tiptap';
  import { tipTapExtensions } from '@u22n/tiptap/extensions';
  import { useVModel } from '@vueuse/core';
  import { watch } from '#imports';

  const props = defineProps<{
    modelValue: tiptapVue3.JSONContent;
  }>();

  const emit = defineEmits<{
    (e: 'update:modelValue', value?: tiptapVue3.JSONContent): void;
  }>();

  const content = useVModel(props, 'modelValue', emit);

  const editor = tiptapVue3.useEditor({
    content: content.value,
    extensions: tipTapExtensions,
    autofocus: true,
    editorProps: {
      attributes: {
        class:
          'max-h-full w-full focus:outline-none p-0 overflow-hidden h-full *:max-w-prose'
      }
    },
    onUpdate: () => {
      emit('update:modelValue', editor.value?.getJSON());
    }
  });

  watch(content, (val) => {
    const isSame = editor.value?.getJSON() === val;
    if (isSame) return;

    editor.value?.commands.setContent(val, false);
  });
</script>

<template>
  <div
    class="border-1 border-base-6 bg-base-1 h-full max-h-full w-full rounded-xl border px-2 py-1 shadow-md">
    <tiptapVue3.EditorContent
      :editor="editor"
      class="h-full max-h-full overflow-y-auto" />
  </div>
</template>
