// apps/web-app/pages/join/index.vue
<script setup lang="ts">
  import { zodSchemas } from '@u22n/utils';
  import {
    navigateTo,
    definePageMeta,
    useNuxtApp,
    ref,
    computed,
    watchDebounced,
    useCookie,
    type Ref,
    onNuxtReady
  } from '#imports';

  const { $trpc } = useNuxtApp();
  definePageMeta({ guest: true });

  const buttonLoading = ref(false);

  //Form Fields
  const usernameValid = ref<boolean | 'remote' | null>(null);
  const usernameValue = ref('');
  const usernameValidationMessage = ref('');
  const termsAccepted = ref(false);

  const formValid = computed(() => {
    return usernameValid.value === true && termsAccepted.value === true;
  });

  //functions
  async function goToNextStep() {
    useCookie('un-join-username', { maxAge: 3600 }).value = usernameValue.value;
    navigateTo('/join/secure');
  }

  async function checkUsername() {
    if (!zodSchemas.username().safeParse(usernameValue.value).success) {
      return;
    }
    const { available, error } =
      await $trpc.auth.signup.checkUsernameAvailability.query({
        username: usernameValue.value
      });
    if (!available) {
      usernameValid.value = false;
      usernameValidationMessage.value = error || 'something went wrong';
    }
    available && (usernameValid.value = true);
  }

  watchDebounced(
    usernameValue,
    async () => {
      if (usernameValid.value === 'remote') {
        await checkUsername();
      }
    },
    {
      debounce: 500,
      maxWait: 5000
    }
  );

  const pageReady: Ref<boolean> = ref(false);
  onNuxtReady(() => {
    pageReady.value = true;
  });
</script>

<template>
  <div class="flex h-full w-full flex-col items-center justify-between p-4">
    <div
      class="flex w-full max-w-72 grow flex-col items-center justify-center gap-8 pb-4 md:max-w-xl">
      <h1 class="mb-4 flex flex-col gap-2 text-center">
        <span class="text-2xl font-medium leading-none">Let's make your</span>
        <span class="font-display text-5xl leading-none">UnInbox</span>
      </h1>
      <h2 class="text-center text-xl font-semibold">Choose your username</h2>
      <div class="flex w-full flex-row justify-stretch gap-2">
        <UnUiTooltip
          text="Choose your username"
          class="w-full">
          <div class="bg-base-9 h-2 w-full rounded" />
        </UnUiTooltip>
        <UnUiTooltip
          text="Secure your account"
          class="w-full">
          <div class="bg-base-5 h-2 w-full rounded" />
        </UnUiTooltip>
        <UnUiTooltip
          text="Set up your organization"
          class="w-full">
          <div class="bg-base-5 h-2 w-full rounded" />
        </UnUiTooltip>
        <UnUiTooltip
          text="Create your profile"
          class="w-full">
          <div class="bg-base-5 h-2 w-full rounded" />
        </UnUiTooltip>
      </div>
      <div class="flex flex-col gap-2">
        <p class="text-center">
          This will be your username across the whole Un ecosystem.
        </p>
        <p class="text-center">
          It's yours personally and can join as many organizations as you want.
        </p>
      </div>
      <UnUiInput
        v-model:value="usernameValue"
        v-model:valid="usernameValid"
        v-model:validationMessage="usernameValidationMessage"
        width="full"
        icon="ph:at"
        label="Username"
        helper="Can only contain letters and numbers."
        placeholder=""
        :remote-validation="true"
        :schema="zodSchemas.username()" />
      <div class="flex flex-row gap-2">
        <NuxtUiCheckbox
          v-model="termsAccepted"
          :disabled="!usernameValid" />
        <span class="text-sm">
          I agree to the UnInbox
          <a
            href="https://legal.u22n.com/uninbox/terms"
            target="_blank">
            Terms of Service
          </a>
          and
          <a
            href="https://legal.u22n.com/uninbox/privacy"
            target="_blank">
            Privacy Policy </a
          >.
        </span>
      </div>

      <div class="mt-3 flex w-full flex-col gap-2">
        <UnUiButton
          label="I like it"
          icon="i-ph-check"
          :loading="buttonLoading"
          :disabled="!formValid"
          block
          @click="goToNextStep()" />
        <UnUiButton
          label="Sign in instead"
          variant="ghost"
          block
          @click="navigateTo('/')" />
        <UnUiButton
          label="Sign up for EU only datahosting"
          variant="ghost"
          size="sm"
          block
          @click="navigateTo('/eu')" />
      </div>
    </div>
  </div>
</template>

// apps/web/src/app/join/page.tsx
'use client';

import {
  Tooltip,
  TooltipContent,
  TooltipTrigger
} from '@/src/components/shadcn-ui/tooltip';
import { Button } from '@/src/components/shadcn-ui/button';
import { Checkbox } from '@/src/components/shadcn-ui/checkbox';
import Stepper from './_components/stepper';
import { Check, Plus, Info } from '@phosphor-icons/react';
import { useDebounce } from '@uidotdev/usehooks';
import { api } from '@/src/lib/trpc';
import { useState, useEffect } from 'react';
import { toast } from 'sonner';
import { zodSchemas } from '@u22n/utils/zodSchemas';
import { useCookies } from 'next-client-cookies';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import useLoading from '@/src/hooks/use-loading';
import { Input } from '@/src/components/shadcn-ui/input';
import { cn } from '@/src/lib/utils';
import { Label } from '@/src/components/shadcn-ui/label';
import { datePlus } from '@u22n/utils/ms';

export default function Page() {
  const [username, setUsername] = useState<string>();
  const [agree, setAgree] = useState(false);
  const cookies = useCookies();
  const router = useRouter();
  const checkUsernameApi = api.useUtils().auth.signup.checkUsernameAvailability;
  const debouncedUsername = useDebounce(username, 1000);

  const {
    loading: usernameLoading,
    data: usernameData,
    error: usernameError,
    run: checkUsername
  } = useLoading(async (signal) => {
    if (!debouncedUsername) return;
    const parsed = zodSchemas.username().safeParse(debouncedUsername);
    if (!parsed.success) {
      return {
        error: parsed.error.issues[0]?.message ?? null,
        available: false
      };
    }
    return await checkUsernameApi.fetch(
      { username: debouncedUsername },
      { signal }
    );
  });

  useEffect(() => {
    if (typeof debouncedUsername === 'undefined') return;
    checkUsername({ clearData: true, clearError: true });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [debouncedUsername]);

  useEffect(() => {
    if (usernameError) {
      toast.error(usernameError.message);
    }
  }, [usernameError]);

  function nextStep() {
    if (!username) return;
    cookies.set('un-join-username', username, {
      expires: datePlus('15 minutes')
    });
    router.push('/join/secure');
  }

  return (
    <div className="mx-auto flex w-full max-w-[560px] flex-col gap-3 px-4">
      <span className="text-bold mt-3 text-lg font-bold">
        Choose Your Username
      </span>
      <Stepper
        step={1}
        total={4}
      />
      <div className="flex flex-col gap-1">
        <span className="text-pretty font-medium">
          This will be your username across the whole Un ecosystem.
        </span>
        <span className="text-pretty font-medium">
          It&apos;s yours personally and can join as many organizations as you
          want.
        </span>
      </div>
      <div className="flex-col items-start gap-2 py-4 text-start">
        <span className="text-sm font-bold">Username</span>
        <div className="flex">
          <Input
            className="w-full"
            onChange={(e) => setUsername(e.target.value)}
          />
          <Tooltip>
            <TooltipTrigger className="p-2">
              <Info size={20} />
            </TooltipTrigger>
            <TooltipContent>
              Username can only contain letters, numbers, and underscores.
            </TooltipContent>
          </Tooltip>
        </div>

        {!usernameData && usernameLoading && (
          <div className="text-muted-foreground text-sm font-bold">
            Checking...
          </div>
        )}

        {usernameData && !usernameLoading && (
          <div className="flex items-center gap-1">
            {usernameData.available ? (
              <Check
                size={16}
                className="text-green-10"
              />
            ) : (
              <Plus
                size={16}
                className="text-red-10 rotate-45"
              />
            )}
            <div
              className={cn(
                'text-sm font-bold',
                usernameData.available ? 'text-green-10' : 'text-red-10'
              )}>
              {usernameData.available ? 'Looks good!' : usernameData.error}
            </div>
          </div>
        )}

        {usernameError && !usernameLoading && (
          <div className="text-red-10 text-sm font-bold">
            {usernameError.message}
          </div>
        )}
      </div>

      <Label className="mx-auto py-3">
        <div className="flex gap-2">
          <Checkbox
            checked={agree}
            onCheckedChange={(e) => setAgree(!!e)}
            disabled={!usernameData?.available}
          />
          <span>
            I agree to the UnInbox{' '}
            <a
              href="https://legal.u22n.com/uninbox/terms"
              target="_blank"
              className="underline">
              Terms of Service
            </a>{' '}
            and{' '}
            <a
              href="https://legal.u22n.com/uninbox/privacy"
              target="_blank"
              className="underline">
              Privacy Policy
            </a>
            .
          </span>
        </div>
      </Label>

      <Button
        disabled={!usernameData?.available || !agree}
        onClick={nextStep}>
        I like it!
      </Button>
      <Button
        variant="link"
        className="mx-auto my-2 w-fit p-2">
        <Link href="/">Sign in instead</Link>
      </Button>
    </div>
  );
}
