// apps/web-app/components/un/editor.vue
<script setup lang="ts">
  import { tiptapVue3 } from '@u22n/tiptap';
  import { tipTapExtensions } from '@u22n/tiptap/extensions';
  import { useVModel } from '@vueuse/core';
  import { watch } from '#imports';

  const props = defineProps<{
    modelValue: tiptapVue3.JSONContent;
  }>();

  const emit = defineEmits<{
    (e: 'update:modelValue', value?: tiptapVue3.JSONContent): void;
  }>();

  const content = useVModel(props, 'modelValue', emit);

  const editor = tiptapVue3.useEditor({
    content: content.value,
    extensions: tipTapExtensions,
    autofocus: true,
    editorProps: {
      attributes: {
        class:
          'max-h-full w-full focus:outline-none p-0 overflow-hidden h-full *:max-w-prose'
      }
    },
    onUpdate: () => {
      emit('update:modelValue', editor.value?.getJSON());
    }
  });

  watch(content, (val) => {
    const isSame = editor.value?.getJSON() === val;
    if (isSame) return;

    editor.value?.commands.setContent(val, false);
  });
</script>

<template>
  <div
    class="border-1 border-base-6 bg-base-1 h-full max-h-full w-full rounded-xl border px-2 py-1 shadow-md">
    <tiptapVue3.EditorContent
      :editor="editor"
      class="h-full max-h-full overflow-y-auto" />
  </div>
</template>

// apps/web/src/components/shared/editor.tsx
'use client';

import {
  EditorRoot,
  EditorCommand,
  EditorCommandEmpty,
  EditorContent,
  type JSONContent,
  type EditorFunctions
} from '@u22n/tiptap/react/components';
import { ScrollArea } from '@/src/components/shadcn-ui/scroll-area';
import { forwardRef } from 'react';

interface EditorProp {
  initialValue?: JSONContent;
  onChange: (value: JSONContent) => void;
}

export const Editor = forwardRef<EditorFunctions, EditorProp>(
  ({ initialValue, onChange }, ref) => {
    return (
      <ScrollArea>
        <EditorRoot>
          <EditorContent
            className="h-full w-full p-2"
            initialContent={initialValue}
            editorProps={{
              attributes: {
                class: `prose dark:prose-invert focus:outline-none max-w-full text-base-12 prose-p:my-0 prose-a:decoration-blue-9`
              }
            }}
            onUpdate={({ editor }) => onChange(editor.getJSON())}
            ref={ref}>
            <EditorCommand className="border-base-5 bg-base-1 z-50 h-auto max-h-[330px] overflow-y-auto rounded-md border px-1 py-2 shadow-md transition-all">
              <EditorCommandEmpty className="px-2">
                No results
              </EditorCommandEmpty>
            </EditorCommand>
          </EditorContent>
        </EditorRoot>
      </ScrollArea>
    );
  }
);

Editor.displayName = 'Editor';
