// ee/apps/command/src/app/password-reset/page.tsx
'use client';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Suspense, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { serialize } from 'superjson';
import { api } from '@/lib/trpc';
import { toast } from 'sonner';

export default function Page() {
  const [username, setUsername] = useState<string>('');
  const { data, error, isLoading, refetch } =
    api.accounts.getFullAccountData.useQuery({ username }, { enabled: false });

  const {
    data: passwordData,
    mutate: resetPassword,
    isPending: isPendingPassword
  } = api.accounts.resetPassword.useMutation({
    onSuccess: () => {
      toast.success('Password reset successful');
      void refetch();
    },
    onError: (error) => {
      toast.error(error.message);
    }
  });

  const {
    data: twoFaData,
    isPending: isPending2Fa,
    mutate: reset2Fa
  } = api.accounts.reset2fa.useMutation({
    onSuccess: () => {
      toast.success('2FA reset successful');
      void refetch();
    },
    onError: (error) => {
      toast.error(error.message);
    }
  });

  return (
    <div className="flex flex-col gap-4 p-4 pb-4">
      <h1 className="text-2xl font-bold">Password & 2FA Reset</h1>
      <div className="flex w-fit gap-2">
        <Input
          value={username}
          onChange={(e) => setUsername(e.target.value)}
          placeholder="Enter Username"
        />
        <Button
          onClick={() => refetch()}
          disabled={isLoading}>
          {isLoading ? 'Searching...' : 'Search'}
        </Button>
      </div>
      {error && <div className="text-red-500">{error.message}</div>}
      {data && (
        <>
          <div className="whitespace-pre border p-2 font-mono">
            {JSON.stringify(serialize(data).json, null, 2)}
          </div>
          <div className="flex gap-2">
            <Button
              onClick={() => {
                if (!data.account) {
                  toast.error('Account not found');
                  return;
                }
                const sure = confirm(
                  `You are about to reset the password for ${username}. Are you sure?`
                );
                if (!sure) return;
                resetPassword({ username });
              }}
              disabled={isPendingPassword}
              className="w-fit">
              {isPendingPassword ? 'Resetting Password...' : 'Reset Password'}
            </Button>
            <Button
              onClick={() => {
                const sure = confirm(
                  `You are about to reset the 2FA for ${username}. Are you sure?`
                );
                if (!sure) return;
                reset2Fa({ username });
              }}
              disabled={isPending2Fa}
              className="w-fit">
              {isPending2Fa ? 'Resetting 2FA...' : 'Reset 2FA'}
            </Button>
          </div>
        </>
      )}
      {passwordData && (
        <div>
          New Password:{' '}
          <span className="select-all border p-2 font-mono">
            {passwordData.newPassword}
          </span>
        </div>
      )}
      {twoFaData && (
        <div>
          2FA URI:{' '}
          <span className="select-all border p-2 font-mono">
            {twoFaData.uri}
          </span>
          <Suspense fallback={<div>Loading QR code...</div>}>
            <QRCodeSVG value={twoFaData.uri} />
          </Suspense>
        </div>
      )}
    </div>
  );
}

// ee/apps/command/pages/password-reset.vue
<script setup lang="ts">
  // Seriously, why the fu*k i need to do this
  declare const window: {
    confirm: (message: string) => boolean;
  };

  import { ref, useNuxtApp, useToast } from '#imports';
  import { serialize } from 'superjson';
  import { toDataURL } from 'qrcode';
  const { $trpc } = await useNuxtApp();

  const username = ref<string>('');

  const functionResult = ref({});
  const toast = useToast();

  const accountData = ref<{} | null>(null);
  const qrCode = ref<string>('');

  async function getAccountData() {
    const { data } = await $trpc.accounts.getFullAccountData.useQuery({
      username: username.value
    });
    accountData.value = data.value || {};
  }

  async function resetPassword() {
    if (!accountData.value) return;
    const sure = window.confirm(
      `You are about to reset the password for ${username.value}. Are you sure?`
    );
    if (!sure) return;
    const result = await $trpc.accounts.resetPassword.mutate({
      username: username.value
    });
    if (!result) {
      toast.add({
        title: 'Error',
        description: 'failed',
        color: 'red',
        timeout: 5000
      });
    }
    functionResult.value = result;
    toast.add({
      title: 'Success',
      description: 'success',
      color: 'green',
      timeout: 5000
    });
  }
  async function reset2FA() {
    if (!accountData.value) return;
    const sure = window.confirm(
      `You are about to reset the 2FA for ${username.value}. Are you sure?`
    );
    if (!sure) return;
    const result = await $trpc.accounts.reset2fa.mutate({
      username: username.value
    });
    if (!result) {
      toast.add({
        title: 'Error',
        description: 'failed',
        color: 'red',
        timeout: 5000
      });
    }
    functionResult.value = result;
    qrCode.value = await toDataURL(result.uri);
    toast.add({
      title: 'Success',
      description: 'success',
      color: 'green',
      timeout: 5000
    });
  }
</script>

<template>
  <div class="flex flex-col gap-8 py-4">
    <h1 class="font-display">Password Reset</h1>
    <div class="flex flex-row gap-4">
      <NuxtUiInput
        v-model="username"
        label="username"
        placeholder="username" />
      <NuxtUiButton
        label="Get Account"
        @click="getAccountData()" />
    </div>
    <pre>
      {{ serialize(accountData).json }}
    </pre>
    <div class="flex w-fit gap-2">
      <NuxtUiButton
        label="Reset Password"
        :disabled="!accountData"
        @click="resetPassword()" />
      <NuxtUiButton
        label="Reset 2FA"
        :disabled="!accountData"
        @click="reset2FA()" />
    </div>
    <pre>
      {{ serialize(functionResult).json }}
    </pre>
    <div v-if="qrCode">
      <img :src="qrCode" />
    </div>
  </div>
</template>
