// apps/web/app/join/page.tsx
'use client';

import {
  Button,
  Flex,
  Spinner,
  Text,
  TextField,
  Tooltip,
  Checkbox
} from '@radix-ui/themes';
import Stepper from './Stepper';
import { Check, Plus, Info } from 'lucide-react';
import { useDebounceCallback } from 'usehooks-ts';
import { api } from '@/lib/trpc';
import { useState, useRef } from 'react';
import { toast } from 'sonner';
import { zodSchemas } from '@u22n/utils';
import { useCookies } from 'next-client-cookies';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

export default function Page() {
  const username = useRef('');
  const [usernameLoading, setUsernameLoading] = useState(false);
  const [usernameData, setUsernameData] = useState<{
    available: boolean;
    error: string | null;
  }>({
    available: false,
    error: null
  });
  const [hasData, setHasData] = useState(false);
  const [agree, setAgree] = useState(false);
  const cookies = useCookies();
  const router = useRouter();

  const checkUsernameApi = api.useUtils().auth.signup.checkUsernameAvailability;

  const checkUsername = useDebounceCallback(
    async (username: string) => {
      const parsed = zodSchemas.username().safeParse(username);
      if (!parsed.success) {
        setUsernameData({
          error: parsed.error.issues[0]?.message ?? null,
          available: false
        });
        setHasData(true);
        return;
      }

      setUsernameLoading(true);
      await checkUsernameApi
        .fetch({ username })
        .then((data) => {
          setUsernameData(data);
        })
        .catch((error: Error) => {
          toast.error(error.message);
        })
        .finally(() => setUsernameLoading(false));
      setHasData(true);
    },
    1000,
    { maxWait: 7500 }
  );

  function nextStep() {
    cookies.set('un-join-username', username.current);
    router.push('/join/secure');
  }

  return (
    <Flex
      direction="column"
      gap="3"
      className="mx-auto w-full max-w-[560px] px-4">
      <Text
        mt="3"
        size="4"
        weight="bold">
        Choose Your Username
      </Text>
      <Stepper
        step={1}
        total={4}
      />
      <Flex
        direction="column"
        gap="1">
        <Text
          size="3"
          className="text-pretty"
          weight="medium">
          This will be your username across the whole Un ecosystem.
        </Text>
        <Text
          size="3"
          className="text-pretty"
          weight="medium">
          It&apos;s yours personally and can join as many organizations as you
          want.
        </Text>
      </Flex>
      <Flex
        direction="column"
        align="start"
        className="py-4"
        gap="1">
        <Text
          size="3"
          weight="bold">
          Username
        </Text>

        <TextField.Root
          className="w-full"
          onChange={(e) => {
            username.current = e.target.value;
            setHasData(false);
            if (!username.current) return;
            void checkUsername(username.current);
          }}
          color={
            hasData ? (usernameData.available ? 'green' : 'red') : undefined
          }>
          <TextField.Slot />
          <TextField.Slot>
            <Tooltip content="Can contain only letters, numbers, dots, hyphens and underscore">
              <Info size={16} />
            </Tooltip>
          </TextField.Slot>
        </TextField.Root>

        {!hasData && usernameLoading && (
          <Flex
            align="center"
            gap="1">
            <Spinner loading />
            <Text
              weight="bold"
              size="2">
              Checking...
            </Text>
          </Flex>
        )}

        {hasData && !usernameLoading && (
          <Flex
            align="center"
            gap="1">
            {usernameData.available ? (
              <Check
                size={16}
                className="stroke-green-11"
              />
            ) : (
              <Plus
                size={16}
                className="stroke-red-11 rotate-45"
              />
            )}

            <Text
              className={
                !usernameData.available ? 'text-red-11' : 'text-green-11'
              }
              weight="bold"
              size="2">
              {usernameData.available ? 'Looks good!' : usernameData.error}
            </Text>
          </Flex>
        )}
      </Flex>

      <Text
        as="label"
        size="2"
        className="mx-auto py-3">
        <Flex
          as="span"
          gap="2">
          <Checkbox
            size="1"
            checked={agree}
            onCheckedChange={(e) => setAgree(!!e)}
            disabled={!usernameData.available}
          />
          <span>
            I agree to the UnInbox{' '}
            <a
              href="https://legal.u22n.com/uninbox/terms"
              target="_blank"
              className="underline">
              Terms of Service
            </a>{' '}
            and{' '}
            <a
              href="https://legal.u22n.com/uninbox/privacy"
              target="_blank"
              className="underline">
              Privacy Policy
            </a>
            .
          </span>
        </Flex>
      </Text>

      <Button
        disabled={!usernameData.available || !agree}
        onClick={nextStep}>
        I like it!
      </Button>
      <Button
        variant="ghost"
        my="2"
        className="mx-auto w-fit p-2">
        <Link href="/">Sign in instead</Link>
      </Button>
    </Flex>
  );
}

// apps/web-app/pages/join/index.vue
<script setup lang="ts">
  import { zodSchemas } from '@u22n/utils';
  import {
    navigateTo,
    definePageMeta,
    useNuxtApp,
    ref,
    computed,
    watchDebounced,
    useCookie,
    type Ref,
    onNuxtReady
  } from '#imports';

  const { $trpc } = useNuxtApp();
  definePageMeta({ guest: true });

  const buttonLoading = ref(false);

  //Form Fields
  const usernameValid = ref<boolean | 'remote' | null>(null);
  const usernameValue = ref('');
  const usernameValidationMessage = ref('');
  const termsAccepted = ref(false);

  const formValid = computed(() => {
    return usernameValid.value === true && termsAccepted.value === true;
  });

  //functions
  async function goToNextStep() {
    useCookie('un-join-username', { maxAge: 3600 }).value = usernameValue.value;
    navigateTo('/join/secure');
  }

  async function checkUsername() {
    if (!zodSchemas.username().safeParse(usernameValue.value).success) {
      return;
    }
    const { available, error } =
      await $trpc.auth.signup.checkUsernameAvailability.query({
        username: usernameValue.value
      });
    if (!available) {
      usernameValid.value = false;
      usernameValidationMessage.value = error || 'something went wrong';
    }
    available && (usernameValid.value = true);
  }

  watchDebounced(
    usernameValue,
    async () => {
      if (usernameValid.value === 'remote') {
        await checkUsername();
      }
    },
    {
      debounce: 500,
      maxWait: 5000
    }
  );

  const pageReady: Ref<boolean> = ref(false);
  onNuxtReady(() => {
    pageReady.value = true;
  });
</script>

<template>
  <div class="flex h-full w-full flex-col items-center justify-between p-4">
    <div
      class="flex w-full max-w-72 grow flex-col items-center justify-center gap-8 pb-4 md:max-w-xl">
      <h1 class="mb-4 flex flex-col gap-2 text-center">
        <span class="text-2xl font-medium leading-none">Let's make your</span>
        <span class="font-display text-5xl leading-none">UnInbox</span>
      </h1>
      <h2 class="text-center text-xl font-semibold">Choose your username</h2>
      <div class="flex w-full flex-row justify-stretch gap-2">
        <UnUiTooltip
          text="Choose your username"
          class="w-full">
          <div class="bg-base-9 h-2 w-full rounded" />
        </UnUiTooltip>
        <UnUiTooltip
          text="Secure your account"
          class="w-full">
          <div class="bg-base-5 h-2 w-full rounded" />
        </UnUiTooltip>
        <UnUiTooltip
          text="Set up your organization"
          class="w-full">
          <div class="bg-base-5 h-2 w-full rounded" />
        </UnUiTooltip>
        <UnUiTooltip
          text="Create your profile"
          class="w-full">
          <div class="bg-base-5 h-2 w-full rounded" />
        </UnUiTooltip>
      </div>
      <div class="flex flex-col gap-2">
        <p class="text-center">
          This will be your username across the whole Un ecosystem.
        </p>
        <p class="text-center">
          It's yours personally and can join as many organizations as you want.
        </p>
      </div>
      <UnUiInput
        v-model:value="usernameValue"
        v-model:valid="usernameValid"
        v-model:validationMessage="usernameValidationMessage"
        width="full"
        icon="ph:at"
        label="Username"
        helper="Can only contain letters and numbers."
        placeholder=""
        :remote-validation="true"
        :schema="zodSchemas.username()" />
      <div class="flex flex-row gap-2">
        <NuxtUiCheckbox
          v-model="termsAccepted"
          :disabled="!usernameValid" />
        <span class="text-sm">
          I agree to the UnInbox
          <a
            href="https://legal.u22n.com/uninbox/terms"
            target="_blank">
            Terms of Service
          </a>
          and
          <a
            href="https://legal.u22n.com/uninbox/privacy"
            target="_blank">
            Privacy Policy </a
          >.
        </span>
      </div>

      <div class="mt-3 flex w-full flex-col gap-2">
        <UnUiButton
          label="I like it"
          icon="i-ph-check"
          :loading="buttonLoading"
          :disabled="!formValid"
          block
          @click="goToNextStep()" />
        <UnUiButton
          label="Sign in instead"
          variant="ghost"
          block
          @click="navigateTo('/')" />
        <UnUiButton
          label="Sign up for EU only datahosting"
          variant="ghost"
          size="sm"
          block
          @click="navigateTo('/eu')" />
      </div>
    </div>
  </div>
</template>
