// apps/web-app/pages/[orgSlug]/convo/index.vue
<script setup lang="ts">
  const orgSlug = useRoute().params.orgSlug as string;
</script>
<template>
  <div
    class="col-span-2 flex h-full w-full flex-col items-center justify-center gap-2 pl-4">
    <div class="col-span-2 pl-4">Select a conversation from the left, or</div>
    <button
      class="border-1 border-base-7 bg-base-3 flex w-full max-w-80 flex-row items-center justify-center gap-4 rounded p-2"
      @click="navigateTo(`/${orgSlug}/convo/new`)">
      <UnUiIcon
        name="i-ph-plus"
        size="20" />
      <p class="text-sm">Start new</p>
    </button>
  </div>
</template>

// apps/web/src/app/[orgShortcode]/convo/page.tsx
'use client';
import { useOrgScopedRouter } from '@/src/hooks/use-params';
import { Button } from '@/src/components/shadcn-ui/button';
import { useIsMobile } from '@/src/hooks/use-is-mobile';
import Link from 'next/link';

export default function Page() {
  const { scopedUrl } = useOrgScopedRouter();
  const isMobile = useIsMobile();

  return isMobile ? null : (
    <div className="flex flex-1 flex-col items-center justify-center gap-2 p-4 text-center">
      <Button asChild>
        <Link href={scopedUrl(`/convo/new`, true)}>New Conversation</Link>
      </Button>
    </div>
  );
}
