// apps/web-app/pages/[orgShortcode]/convo/index.vue
<script setup lang="ts">
  import { navigateTo, useRoute } from '#imports';

  const orgShortcode = useRoute().params.orgShortcode as string;
</script>
<template>
  <div
    class="col-span-2 flex h-full w-full flex-col items-center justify-center gap-2 pl-4">
    <div class="col-span-2 pl-4">Select a conversation from the left, or</div>
    <button
      class="border-1 border-base-7 bg-base-3 flex w-full max-w-80 flex-row items-center justify-center gap-4 rounded p-2"
      @click="navigateTo(`/${orgShortcode}/convo/new`)">
      <UnUiIcon
        name="i-ph-plus"
        size="20" />
      <p class="text-sm">Start new</p>
    </button>
  </div>
</template>

// apps/web/src/app/[orgShortCode]/convo/page.tsx
'use client';
import { useGlobalStore } from '@/src/providers/global-store-provider';
import { Button, Text } from '@radix-ui/themes';
import Link from 'next/link';

export default function Page() {
  const orgShortCode = useGlobalStore((state) => state.currentOrg.shortCode);

  return (
    <div className="flex h-full w-full flex-col items-center justify-center gap-2 p-4">
      <Text
        weight="bold"
        size="2">
        Select a Convo from Sidebar or Create a New One
      </Text>
      <Link href={`/${orgShortCode}/convo/new`}>
        <Button>Create New Convo</Button>
      </Link>
    </div>
  );
}
