// apps/web-app/pages/[orgSlug]/settings/org/mail/addresses/index.vue
<script setup lang="ts">
  import { navigateTo, ref, useNuxtApp, useRoute, watch } from '#imports';

  const { $trpc } = useNuxtApp();

  const orgSlug = useRoute().params.orgSlug as string;

  const {
    data: orgEmailIdentities,
    pending,
    refresh
  } = await $trpc.org.mail.emailIdentities.getOrgEmailIdentities.useLazyQuery(
    {},
    { server: false }
  );

  const tableColumns = [
    {
      key: 'address',
      label: 'Address',
      sortable: true
    },
    {
      key: 'domain',
      label: 'Domain',
      sortable: true
    },
    {
      key: 'sendName',
      label: 'SendName',
      sortable: true
    },
    {
      key: 'destination',
      label: 'Destination',
      sortable: true
    },
    {
      key: 'catchAll',
      sortable: true
    }
  ];

  interface TableRow {
    publicId: string;
    address: string;
    domain: string;
    sendName: string | null;
    catchAll: boolean;
    destination: string;
  }

  const tableRows = ref<TableRow[]>([]);
  watch(orgEmailIdentities, (newResults) => {
    if (newResults?.emailIdentityData) {
      tableRows.value = [];
      for (const identity of newResults.emailIdentityData) {
        tableRows.value.push({
          publicId: identity.publicId,
          address: identity.username,
          domain: identity.domainName,
          sendName: identity.sendName,
          catchAll: identity.isCatchAll,
          destination:
            identity.routingRules.description || identity.routingRules.name
        });
      }
    }
  });
  function select(row: (typeof tableRows.value)[number]) {
    navigateTo(`/${orgSlug}/settings/org/mail/addresses/${row.publicId}`);
  }

  const addNewModalOpen = ref(false);
  const closeModal = () => {
    addNewModalOpen.value = false;
    refresh();
  };

  // TODO: set the destinations column to be an avatar list of users and groups
</script>

<template>
  <div class="flex h-full w-full flex-col items-start gap-8 p-4">
    <div class="flex w-full flex-row items-center justify-between">
      <div class="flex flex-col gap-1">
        <span class="font-display text-2xl">Addresses</span>
        <span class="text-sm">Manage your organization's email addresses</span>
      </div>

      <div class="flex flex-row items-center gap-4">
        <UnUiButton
          label="Add new"
          @click="addNewModalOpen = true" />
        <UnUiModal v-model="addNewModalOpen">
          <template #header>
            <span class="">Add new email address</span>
          </template>
          <SettingsAddNewEmail
            lazy
            @close="closeModal()" />
        </UnUiModal>
      </div>
    </div>
    <div class="flex w-full flex-col gap-4 overflow-y-auto">
      <NuxtUiTable
        :columns="tableColumns"
        :rows="tableRows"
        :loading="pending"
        class=""
        @select="select">
        <template #address-data="{ row }">
          <span class="">{{ row.address }}</span>
        </template>
        <template #catchAll-data="{ row }">
          <UnUiBadge
            v-if="row.catchAll"
            :label="row.catchAll" />
          <span v-if="!row.catchAll"></span>
        </template>
        <template #domain-data="{ row }">
          <span class="">@{{ row.domain }}</span>
        </template>
      </NuxtUiTable>
    </div>
  </div>
</template>

// apps/web/src/app/[orgShortCode]/settings/org/mail/addresses/page.tsx
'use client';

import Metadata from '@/src/components/metadata';
import { DataTable } from '@/src/components/shared/table';
import { api } from '@/src/lib/trpc';
import { useGlobalStore } from '@/src/providers/global-store-provider';
import { columns } from './_components/columns';
import { AddEmailModal } from './_components/add-address-modal';

export default function Page() {
  const orgShortCode = useGlobalStore((state) => state.currentOrg.shortCode);
  const { data: emailsList, isLoading } =
    api.org.mail.emailIdentities.getOrgEmailIdentities.useQuery({
      orgShortCode
    });

  return (
    <div className="flex w-full flex-col gap-2 p-4">
      <Metadata
        title="Org Settings - Addresses"
        description="Manage your organization"
      />
      <div className="flex w-full justify-between">
        <div className="flex flex-col gap-2">
          <h1 className="font-display text-3xl leading-5">Addresses</h1>
          <div>Manage Your Org Email Addresses</div>
        </div>
        <AddEmailModal />
      </div>
      {isLoading && <div>Loading...</div>}
      {emailsList && (
        <DataTable
          columns={columns}
          data={emailsList.emailIdentityData ?? []}
          linkTo={(row) =>
            `/${orgShortCode}/settings/org/mail/addresses/${row.publicId}`
          }
        />
      )}
    </div>
  );
}
