// apps/web/app/[orgShortCode]/settings/user/addresses/page.tsx
'use client';

import {
  Button,
  Flex,
  Heading,
  Text,
  Card,
  Spinner,
  Dialog
} from '@radix-ui/themes';
import { DataTable } from './table';
import { useGlobalStore } from '@/providers/global-store-provider';
import { api } from '@/lib/trpc';
import { columns } from './columns';
import useAwaitableModal from '@/hooks/use-awaitable-modal';
import Link from 'next/link';
import { toast } from 'sonner';
import { useState } from 'react';

export default function Page() {
  const username = useGlobalStore((state) => state.user.username);
  const currentOrg = useGlobalStore((state) => state.currentOrg);

  const { data: proStatus } = api.org.setup.billing.isPro.useQuery({});
  const [isClaiming, setIsClaiming] = useState(false);

  const {
    data: personalAddresses,
    isLoading: personalAddressesLoading,
    error: personalAddressesError,
    refetch: refetchPersonalAddresses
  } = api.account.addresses.getPersonalAddresses.useQuery({});

  const { ModalRoot, openModal: claimAddress } = useAwaitableModal<
    unknown,
    { address: string }
  >(({ open, onClose, onResolve, args }) => {
    const { mutateAsync: claimAddressConfirm } =
      api.account.addresses.claimPersonalAddress.useMutation({
        onSuccess: async () => {
          await refetchPersonalAddresses();
          setIsClaiming(false);
        }
      });

    return (
      <Dialog.Root
        open={open}
        onOpenChange={(open) => {
          if (!open) {
            onClose();
          }
        }}>
        <Dialog.Content className="w-full max-w-96 p-4">
          <Dialog.Title
            className="mx-auto w-fit py-2"
            size="2">
            Do you want to claim{' '}
            <span className="underline">{args?.address}</span> ?
          </Dialog.Title>

          <Flex
            gap="4"
            direction="column">
            <Text
              size="2"
              as="div">
              You are about to link {args?.address} to the Org {currentOrg.name}
              . This action is irreversible.
            </Text>
            <Text
              size="2"
              as="div">
              If you&apos;re removed from this organization in the future,
              you&apos;ll lose all associated conversations. Our support team
              may be able to reset the address for use in another organization.
            </Text>

            <Text
              size="2"
              as="div">
              We suggest to claim your personal addresses with a personal Org.
              You can{' '}
              <Link
                className="underline"
                href="/">
                create a personal Org
              </Link>{' '}
              if you don&apos;t have one already.
            </Text>

            <Text
              size="2"
              as="div"
              color="red">
              Make sure you want to claim this address with {currentOrg.name},
              if not Cancel this action, change the selected Org and try again.
            </Text>
          </Flex>

          <Flex
            gap="3"
            align="center"
            justify="end"
            className="mt-4">
            <Button
              size="2"
              variant="surface"
              onClick={() => onClose()}>
              Cancel
            </Button>
            <Button
              size="2"
              variant="solid"
              onClick={() => {
                if (!args) return;
                setIsClaiming(true);
                claimAddressConfirm({
                  emailIdentity: args.address
                })
                  .then(() => {
                    onResolve({});
                  })
                  .catch((e: Error) => {
                    toast.error(e.message);
                    onClose();
                  });
              }}
              loading={isClaiming}>
              I Understand, Claim Address
            </Button>
          </Flex>
        </Dialog.Content>
      </Dialog.Root>
    );
  });

  return (
    <Flex
      className="p-4"
      direction="column"
      gap="4">
      <Heading
        as="h1"
        size="5">
        Your Personal Addresses
      </Heading>

      {personalAddressesLoading && <Spinner loading />}

      {personalAddressesError && (
        <Card>
          <Text
            color="red"
            size="2">
            An error occurred while fetching addresses.
          </Text>
          {personalAddressesError?.message}
        </Card>
      )}

      {personalAddresses && personalAddresses.available.free.length > 0 && (
        <Flex
          direction="column"
          gap="2">
          <Heading
            as="h2"
            size="3">
            Available Free Addresses
          </Heading>
          {personalAddresses.available.free.map((domain) => (
            <Card key={domain}>
              <Flex
                direction="row"
                gap="3"
                align="center"
                justify="between">
                <Text className="font-mono">
                  {username}@{domain}
                </Text>
                <Button
                  variant="solid"
                  size="2"
                  onClick={() => {
                    void claimAddress({
                      address: `${username}@${domain}`
                    }).catch(() => null);
                  }}>
                  Claim
                </Button>
              </Flex>
            </Card>
          ))}
        </Flex>
      )}

      {personalAddresses && personalAddresses.available.premium.length > 0 && (
        <Flex
          direction="column"
          gap="2">
          <Heading
            as="h2"
            size="3">
            Available Premium Addresses
          </Heading>
          {personalAddresses.available.premium.map((domain) => (
            <Card key={domain}>
              <Flex
                direction="row"
                gap="3"
                align="center"
                justify="between">
                <Text className="font-mono">
                  {username}@{domain}
                </Text>
                <Button
                  variant="solid"
                  size="2"
                  disabled={
                    !proStatus?.isPro || !personalAddresses.hasUninBonus
                  }>
                  Claim
                </Button>
              </Flex>
            </Card>
          ))}
        </Flex>
      )}

      {personalAddresses && personalAddresses.identities.length > 0 && (
        <>
          <Heading
            as="h2"
            size="3">
            Your claimed addresses
          </Heading>
          <DataTable
            columns={columns}
            data={personalAddresses.identities}
          />
        </>
      )}

      <ModalRoot />
    </Flex>
  );
}

// apps/web-app/pages/[orgSlug]/settings/user/addresses.vue
<script setup lang="ts">
  definePageMeta({
    layout: 'settings'
  });
  import { z } from 'zod';

  const { $trpc, $i18n } = useNuxtApp();
  const { copy, copied, text } = useClipboard();
  const route = useRoute();
  const orgSlug = route.params.orgSlug as string;
  const hasAddresses = ref(false);
  const publicAddressesAvailable = ref<string[]>([]);
  const premiumAddressesAvailable = ref<string[]>([]);

  const {
    data: userAddresses,
    pending,
    error,
    refresh: refreshUserAddresses
  } = await $trpc.user.addresses.getPersonalAddresses.useLazyQuery(
    {},
    { server: false, queryKey: 'getUserAddresses' }
  );

  watch(userAddresses, (newResults) => {
    const username = userAddresses.value?.username?.toLowerCase();
    console.log({ identities: newResults?.identities });
    if (newResults?.identities) {
      hasAddresses.value = true;
    }
    if (!newResults?.identities) {
      hasAddresses.value = false;
    }
    if (newResults?.available.public) {
      publicAddressesAvailable.value = [];
      newResults.available.public.forEach((domain) => {
        publicAddressesAvailable.value.push(`${username}@${domain}`);
      });
    }
    if (newResults?.available.premium) {
      premiumAddressesAvailable.value = [];
      newResults.available.premium.forEach((domain) => {
        premiumAddressesAvailable.value.push(`${username}@${domain}`);
      });
    }
  });

  const preClaimModalOpen = ref(false);
  const emailIdentityToClaim = ref('');
  async function preClaim(emailIdentity: string) {
    emailIdentityToClaim.value = emailIdentity;
    preClaimModalOpen.value = true;
    // open a modal
  }
  async function claim() {
    const toast = useToast();
    toast.add({
      id: 'claiming_email',
      title: 'Setting up your new email address',
      description: `This process could take up to 30 seconds, please dont leave this page.`,
      icon: 'i-ph-clock-countdown',
      timeout: 30000
    });
    const emailIdentity = emailIdentityToClaim.value;
    // check if the email identity is in either of the available lists
    const isInPublicAvailableArray =
      publicAddressesAvailable.value.includes(emailIdentity);
    const isInPremiumAvailableArray =
      premiumAddressesAvailable.value.includes(emailIdentity);
    if (!isInPublicAvailableArray && isInPremiumAvailableArray) {
      return;
    }
    if (isInPremiumAvailableArray && !isPro.value) {
      return;
    }
    const claimResponse =
      await $trpc.user.addresses.claimPersonalAddress.mutate({
        emailIdentity: emailIdentity
      });
    toast.remove('claiming_email');
    refreshUserAddresses();
    toast.add({
      id: 'email_claimed',
      title: 'Success',
      description: `${emailIdentity} has been claimed successfully`,
      icon: 'i-ph-thumbs-up',
      timeout: 5000
    });
    setTimeout(() => {
      preClaimModalOpen.value = false;
    }, 1000);
  }

  const isPro = ref(false);
  if (useEE().config.modules.billing) {
    const { data: isProQuery, pending } =
      await $trpc.org.setup.billing.isPro.useLazyQuery({}, { server: false });

    isPro.value = isProQuery.value?.isPro || false;
  } else {
    isPro.value = true;
  }
</script>

<template>
  <div class="h-full w-full flex flex-col items-start gap-8 p-4">
    <div class="w-full flex flex-row items-center justify-between">
      <span class="text-2xl font-display"> Your Personal Addresses </span>
    </div>
    <UnUiModal v-model="preClaimModalOpen">
      <template #header>
        <div class="flex flex-row items-center gap-2">
          <span class="text-red-500 text-2xl leading-none">
            <UnUiIcon
              name="i-ph-warning-octagon"
              size="xl" />
          </span>
          <span class="text-lg font-semibold leading-none"> Warning! </span>
        </div>
      </template>
      <div class="flex flex-col gap-4">
        <span class="">
          You are about to link
          <span class="font-mono">{{ emailIdentityToClaim }}</span>
          to this organization.
        </span>
        <span class="">
          If you're removed from this organization in the future, you'll lose
          all associated conversations. Our support team may be able to reset
          the address for use in another organization.
        </span>
        <span class="">
          We suggest creating a separate organization for personal addresses.
          <nuxt-link
            class="text-gray-500 text inline-flex flex-row items-center gap-1 text-sm leading-none"
            :to="`/${orgSlug}/settings/org/new`">
            <span>Create a new organization here</span>
            <UnUiIcon
              name="i-ph-arrow-right"
              size="xs" />
          </nuxt-link>
        </span>
        <span class=""> Are you sure you want to proceed? </span>
      </div>
      <template #footer>
        <div class="flex flex-row justify-end gap-2">
          <UnUiButton
            label="Cancel"
            variant="outline"
            @click="preClaimModalOpen = false" />
          <UnUiButton
            label="Add to this organization"
            @click="claim()" />
        </div>
      </template>
    </UnUiModal>
    <div
      v-if="pending"
      class="w-full flex flex-row justify-center gap-4 rounded-xl rounded-tl-2xl bg-base-3 p-8">
      <UnUiIcon
        name="i-svg-spinners:3-dots-fade"
        size="24" />
      <span>Loading</span>
    </div>

    <div
      v-if="!pending"
      class="w-full flex flex-col items-start justify-center gap-8">
      <div
        v-if="!hasAddresses"
        class="w-full flex flex-col items-start justify-center gap-8">
        You have no personal addresses configured, claim them below.
      </div>
      <div
        v-if="
          hasAddresses &&
          (publicAddressesAvailable || premiumAddressesAvailable)
        "
        class="w-full flex flex-col items-start justify-center gap-8">
        You have unclaimed personal addresses, claim them below.
      </div>
      <div
        v-if="publicAddressesAvailable.length"
        class="w-full flex flex-col items-start justify-center gap-8">
        <div class="flex flex-col gap-2">
          <span class="text-sm text-base-11 font-medium uppercase">
            Free email address
          </span>
          <template
            v-for="address of publicAddressesAvailable"
            :key="address">
            <div class="flex flex-row items-center gap-2">
              <div
                class="min-w-[50px] w-fit flex flex-col items-center rounded-lg bg-base-3 px-4 py-2">
                <span class="w-fit break-anywhere text-left font-mono">
                  {{ address }}
                </span>
              </div>
              <UnUiButton
                label="Claim"
                size="md"
                @click="preClaim(address)" />
            </div>
          </template>
        </div>
      </div>
      <div
        v-if="premiumAddressesAvailable.length"
        class="w-full flex flex-col items-start justify-center gap-8">
        <div class="flex flex-col gap-2">
          <span class="text-sm text-base-11 font-medium uppercase">
            Premium email address
          </span>
          <template
            v-for="address of premiumAddressesAvailable"
            :key="address">
            <div class="flex flex-col gap-2">
              <div class="flex flex-row items-center gap-2">
                <div
                  class="min-w-[50px] w-fit flex flex-col items-center rounded-lg bg-base-3 px-4 py-2">
                  <span class="w-fit break-anywhere text-left font-mono">
                    {{ address }}
                  </span>
                </div>
                <UnUiButton
                  label="Claim"
                  :disabled="!isPro"
                  size="md"
                  @click="preClaim(address)" />
              </div>
              <span
                v-if="!isPro"
                class="text-sm">
                This email address is only available to claim when your
                organisation is subscribed to a plan.
              </span>
            </div>
          </template>
        </div>
      </div>
      <div
        v-if="hasAddresses"
        class="w-full flex flex-col items-start justify-center gap-8">
        <div class="flex flex-col gap-4">
          <span class="text-sm text-base-11 font-medium uppercase">
            Personal email addresses
          </span>
          <span class="text-sm">
            You can use these email addresses to send and receive emails with
            the rest of the world.
          </span>
          <span class="text-sm"
            >They are yours personally to keep forever.</span
          >
          {{ userAddresses?.identities }}
          <!-- <div
            v-for="personalEmail of userAddresses?.personalEmailAddresses"
            :key="personalEmail.username + personalEmail.domainName"
            class="flex flex-row items-center gap-2">
            <div
              class="min-w-[50px] w-fit flex flex-col items-center rounded-lg bg-base-3 p-4">
              <span class="w-fit break-anywhere text-left font-mono">
                {{ personalEmail.username }}@{{ personalEmail.domainName }}
              </span>
            </div>
            <UnUiTooltip text="Copy to clipboard">
              <UnUiIcon
                name="i-ph-clipboard"
                size="20"
                @click="
                  copy(`${personalEmail.username}@${personalEmail.domainName}`)
                " />
            </UnUiTooltip>
          </div> -->
        </div>
        <div class="flex flex-col gap-4">
          <!-- <span class="text-sm text-base-11 font-medium uppercase">
            Personal forwarding address
          </span>
          <span class="text-sm">
            Use this email address to forward in emails from another mail
            provider.
          </span>
          <span class="text-sm">
            Any emails forwarded to this address will be processed by your
            personal account.
          </span>
          <div class="flex flex-row items-center gap-2">
            <div
              class="min-w-[50px] w-fit flex flex-col items-center rounded-lg bg-base-3 p-4">
              <span class="w-fit break-anywhere text-left font-mono">
                {{ userAddresses?.personalOrgFwdAddress }}
              </span>
            </div>
            <UnUiTooltip text="Copy to clipboard">
              <UnUiIcon
                name="i-ph-clipboard"
                size="20"
                @click="copy(userAddresses?.personalOrgFwdAddress || '')" />
            </UnUiTooltip>
          </div> -->
        </div>
      </div>
    </div>
  </div>
</template>
