// apps/web-app/pages/[orgShortcode]/convo/new.vue
<script setup lang="ts">
  import {
    computed,
    navigateTo,
    ref,
    useNuxtApp,
    useRoute,
    useToast,
    watch
  } from '#imports';
  import { type ConvoAttachmentUpload } from '~/composables/types';
  import type { tiptapVue3 } from '@u22n/tiptap';
  import { emptyTiptapEditorContent } from '@u22n/tiptap';
  import type { UiColor } from '@u22n/types/ui';
  import { stringify } from 'superjson';
  import { z } from 'zod';
  import type { TypeId } from '@u22n/utils';

  const { $trpc } = useNuxtApp();
  const orgShortcode = useRoute().params.orgShortcode as string;
  const attachmentUploads = ref<ConvoAttachmentUpload[]>([]);
  const currentTotalUploadSize = computed(() => {
    return attachmentUploads.value.reduce((acc, attachment) => {
      return acc + attachment.size;
    }, 0);
  });

  type JSONContent = tiptapVue3.JSONContent;

  // TODO: handle if the domain is not valid/enabled. display the email address in the list but show it as disabled and show a tooltip on hover that says "this domain is not enabled for sending"
  interface OrgEmailIdentities {
    publicId: TypeId<'emailIdentities'>;
    address: string;
    sendName: string | null;
    disabled?: boolean;
  }

  interface ConvoParticipantOrgMembers {
    type: 'orgMember';
    icon: 'i-ph-user';
    publicId: TypeId<'orgMembers'>;
    avatarTimestamp: Date | null;
    profilePublicId: TypeId<'orgMemberProfile'>;
    name: String;
    handle: String;
    title: String | null;
    disabled?: Boolean;
    keywords: String;
    own?: Boolean;
  }
  interface ConvoParticipantOrgGroups {
    type: 'group';
    icon: 'i-ph-users-three';
    publicId: TypeId<'groups'>;
    avatarTimestamp: Date | null;
    name: String;
    description: String | null;
    color: String | null;
    keywords: String;
  }
  interface ConvoParticipantOrgContacts {
    type: 'contact';
    icon: 'i-ph-address-book';
    publicId: TypeId<'contacts'>;
    avatarTimestamp: Date | null;
    name: String;
    address: String;
    keywords: String;
    screenerStatus: 'pending' | 'approve' | 'reject' | null;
  }
  interface NewConvoParticipantEmailAddresses {
    type: 'email';
    icon: 'i-ph-envelope';
    publicId: Number;
    address: String;
    keywords: String;
  }

  type NewConvoParticipant =
    | ConvoParticipantOrgMembers
    | ConvoParticipantOrgGroups
    | ConvoParticipantOrgContacts
    | NewConvoParticipantEmailAddresses;

  //* Data Loading
  // Get email identities
  const { data: userEmailIdentitiesData, status: userEmailIdentitiesStatus } =
    await $trpc.org.mail.emailIdentities.getUserEmailIdentities.useLazyQuery(
      {},
      {
        server: false
      }
    );

  // get list of users
  const { data: orgMembersData, status: orgMembersStatus } =
    await $trpc.org.users.members.getOrgMembersList.useLazyQuery(
      {},
      {
        server: false
      }
    );

  // get list of groups
  const { data: orgGroupsData, status: orgGroupsStatus } =
    await $trpc.org.users.groups.getOrgGroups.useLazyQuery(
      {},
      {
        server: false
      }
    );

  // get list of org contacts
  const { data: orgContactsData } =
    await $trpc.org.contacts.getOrgContacts.useLazyQuery(
      {},
      {
        server: false
      }
    );

  //* List Data
  const orgEmailIdentities = ref<OrgEmailIdentities[]>([]);
  const orgMembers = ref<ConvoParticipantOrgMembers[]>([]);
  const orgGroups = ref<ConvoParticipantOrgGroups[]>([]);
  const orgContacts = ref<ConvoParticipantOrgContacts[]>([]);

  //* Data Watchers
  function setParticipantOptions() {
    participantOptions.value = [
      ...orgMembers.value,
      ...orgGroups.value,
      ...orgContacts.value
    ];
  }

  watch(userEmailIdentitiesData, (newUserEmailIdentitiesData) => {
    orgEmailIdentities.value = [];
    selectedOrgEmailIdentities.value = undefined;
    if (newUserEmailIdentitiesData?.emailIdentities) {
      for (const orgObject of newUserEmailIdentitiesData.emailIdentities) {
        orgEmailIdentities.value.push({
          publicId: orgObject.publicId,
          address: orgObject.username + '@' + orgObject.domainName,
          sendName: orgObject.sendName
        });
      }
    }
    if (newUserEmailIdentitiesData?.defaultEmailIdentity) {
      const defaultEmailIdentityObject =
        newUserEmailIdentitiesData?.emailIdentities.find(
          (emailIdentity) =>
            emailIdentity.publicId ===
            newUserEmailIdentitiesData.defaultEmailIdentity
        );
      selectedOrgEmailIdentities.value = {
        publicId: defaultEmailIdentityObject?.publicId!,
        address:
          defaultEmailIdentityObject?.username +
            '@' +
            defaultEmailIdentityObject?.domainName || '',
        sendName: defaultEmailIdentityObject?.sendName || ''
      };
    }
  });

  watch(orgMembersData, (newOrgMembersData) => {
    if (newOrgMembersData?.ownMembershipId) {
      const ownOrgMemberData = newOrgMembersData.members?.find(
        (member) => member.publicId === newOrgMembersData.ownMembershipId
      );
      if (!ownOrgMemberData) {
        throw new Error('own org member data not found');
      }
      const ownData: ConvoParticipantOrgMembers = {
        type: 'orgMember',
        icon: 'i-ph-user',
        publicId: ownOrgMemberData.publicId,
        profilePublicId: ownOrgMemberData.profile.publicId,
        avatarTimestamp: ownOrgMemberData.profile.avatarTimestamp,
        name:
          ownOrgMemberData.profile?.firstName +
            ' ' +
            ownOrgMemberData.profile?.lastName || '',
        handle: ownOrgMemberData.profile?.handle || '',
        title: ownOrgMemberData.profile?.title || '',
        keywords:
          ownOrgMemberData.profile?.firstName +
          ' ' +
          ownOrgMemberData.profile?.lastName +
          '  @' +
          ownOrgMemberData.profile?.handle +
          ' ' +
          ownOrgMemberData.profile?.title,
        disabled: true,
        own: true
      };
      orgMembers.value.push(ownData);
      // selectedOrgMembers.value = [ownData];
    }
    if (newOrgMembersData?.members) {
      for (const member of newOrgMembersData.members) {
        if (member.publicId === newOrgMembersData.ownMembershipId) {
          continue;
        }
        orgMembers.value.push({
          type: 'orgMember',
          icon: 'i-ph-user',
          publicId: member.publicId,
          profilePublicId: member.profile.publicId,
          avatarTimestamp: member.profile.avatarTimestamp,
          name:
            member.profile?.firstName + ' ' + member.profile?.lastName || '',
          handle: member.profile?.handle || '',
          title: member.profile?.title || '',
          keywords:
            member.profile?.firstName +
            ' ' +
            member.profile?.lastName +
            '  @' +
            member.profile?.handle +
            ' ' +
            member.profile?.title
        });
      }
    }
    setParticipantOptions();
  });

  watch(orgGroupsData, (newOrgGroupsData) => {
    if (newOrgGroupsData?.groups) {
      for (const group of newOrgGroupsData.groups) {
        orgGroups.value.push({
          type: 'group',
          icon: 'i-ph-users-three',
          publicId: group.publicId,
          avatarTimestamp: group.avatarTimestamp,
          name: group.name,
          description: group.description,
          color: group.color,
          keywords: group.name + ' ' + group.description
        });
      }
      setParticipantOptions();
    }
  });

  watch(orgContactsData, (newOrgContactsData) => {
    if (newOrgContactsData?.contacts) {
      for (const contact of newOrgContactsData.contacts) {
        orgContacts.value.push({
          type: 'contact',
          icon: 'i-ph-address-book',
          publicId: contact.publicId,
          avatarTimestamp: contact.avatarTimestamp,
          name:
            contact.setName ||
            contact.name ||
            contact.emailUsername + '@' + contact.emailDomain,
          address: contact.emailUsername + '@' + contact.emailDomain,
          keywords:
            contact.setName +
            ' ' +
            contact.name +
            ' ' +
            contact.emailUsername +
            '@' +
            contact.emailDomain,
          screenerStatus: contact.screenerStatus
        });
      }
      setParticipantOptions();
    }
  });
  // Values
  const participantOptions = ref<NewConvoParticipant[]>([]);
  const selectedParticipants = ref<NewConvoParticipant[]>([]);

  const orgEmailIdentitiesPlaceholder = computed(() => {
    if (userEmailIdentitiesStatus.value !== 'success') {
      return 'Loading Email Identities';
    }
    if (orgEmailIdentities.value.length === 0) {
      return 'No email identities found';
    }
    return 'Select Email Identity';
  });
  const selectedOrgEmailIdentities = ref<OrgEmailIdentities | undefined>(
    undefined
  );

  const hasEmailParticipants = computed(() => {
    return selectedParticipants.value.some(
      (participant) =>
        participant.type === 'email' || participant.type === 'contact'
    );
  });

  const hasEmailParticipantsNoEmailIdentitySelected = computed(() => {
    return (
      selectedParticipants.value.some(
        (participant) =>
          participant.type === 'email' || participant.type === 'contact'
      ) && selectedOrgEmailIdentities.value === undefined
    );
  });

  const emailButNoIdentityRingColor = computed(() => {
    return hasEmailParticipantsNoEmailIdentitySelected.value
      ? 'ring-red-9'
      : 'ring-base-9';
  });

  const participantLabels = computed({
    get: () => selectedParticipants.value,
    set: async (labels) => {
      const promises = labels.map(async (label) => {
        if (label.publicId) {
          return label;
        }
        const keywords = (label as { keywords: string }).keywords;
        const isEmail = z.string().email().safeParse(keywords);
        if (!isEmail.success) {
          return;
        }
        const newEntry: NewConvoParticipantEmailAddresses = {
          type: 'email',
          icon: 'i-ph-envelope',
          publicId: participantOptions.value.length + 1,
          //@ts-ignore
          address: keywords,
          keywords: keywords
        };

        participantOptions.value.push(newEntry);
        const inputElement = document.querySelector('input[name="q"]');
        if (inputElement) {
          // @ts-ignore
          inputElement.value = '';
        }
        return newEntry;
      });
      // @ts-ignore - no idea how to fix this
      selectedParticipants.value = await Promise.all(promises);
    }
  });

  const participantPlaceholder = computed(() => {
    if (
      orgGroupsStatus.value !== 'success' ||
      orgMembersStatus.value !== 'success'
    ) {
      return 'Loading Participants';
    }
    if (orgEmailIdentities.value.length === 0) {
      return 'Search (Select "Send As" to enable email participants)';
    }
    return 'Search or type email...';
  });

  const formValid = computed(() => {
    return (
      !hasEmailParticipantsNoEmailIdentitySelected.value &&
      selectedParticipants.value.length > 0 &&
      conversationTopicInput.value.length > 0 &&
      isTextPresent.value
    );
  });

  const messageEditorData = ref<JSONContent>(emptyTiptapEditorContent);

  const isTextPresent = computed(() => {
    const contentArray = messageEditorData.value?.content;
    if (!contentArray) return false;
    if (contentArray.length === 0) return false;
    if (
      contentArray[0] &&
      (!contentArray[0].content || contentArray[0].content.length === 0)
    )
      return false;
    return true;
  });
  // Topic/subject+

  const conversationTopicInput = ref('');
  const conversationSubjectInputValid = ref(false);

  const actionLoading = ref(false);

  async function createNewConvo(type: 'draft' | 'comment' | 'message') {
    const toast = useToast();
    actionLoading.value = true;
    if (!selectedParticipants.value[0]) {
      actionLoading.value = false;
      toast.add({
        id: 'create_new_convo_fail',
        title: 'Conversation creation failed',
        description: `Please select at least one participant.`,
        color: 'red',
        icon: 'i-ph-warning-circle',
        timeout: 5000
      });
      return;
    }
    const getPublicIdsByType = (
      type: string,
      property: string = 'publicId'
    ) => {
      return selectedParticipants.value
        .filter((participant) => participant.type === type)
        .map((participant: NewConvoParticipant) =>
          participant[property as keyof NewConvoParticipant].toString()
        );
    };

    const convoParticipantsOrgMembersPublicIds =
      getPublicIdsByType('orgMember');
    const convoParticipantsGroupPublicIds = getPublicIdsByType('group');
    const convoParticipantsContactPublicIds = getPublicIdsByType('contact');
    const convoParticipantsEmailPublicIds = getPublicIdsByType(
      'email',
      'address'
    );
    const firstParticipant = selectedParticipants.value[0];
    const firstParticipantPublicId = firstParticipant.publicId?.toString();

    const convoToValue:
      | { type: 'email'; emailAddress: string }
      | { type: 'orgMember' | 'group' | 'contact'; publicId: string } =
      firstParticipant.type === 'email'
        ? {
            type: 'email',
            emailAddress: firstParticipant.address.toString()
          }
        : {
            type: firstParticipant.type,
            publicId: firstParticipantPublicId
          };
    const createNewConvoTrpc = $trpc.convos.createNewConvo.useMutation();

    const createNewConvo = await createNewConvoTrpc.mutate({
      firstMessageType: type,
      to: convoToValue,
      participantsOrgMembersPublicIds: convoParticipantsOrgMembersPublicIds,
      participantsGroupsPublicIds: convoParticipantsGroupPublicIds,
      participantsContactsPublicIds: convoParticipantsContactPublicIds,
      participantsEmails: convoParticipantsEmailPublicIds,
      sendAsEmailIdentityPublicId: selectedOrgEmailIdentities.value?.publicId,
      topic: conversationTopicInput.value,
      message: stringify(messageEditorData.value),
      attachments: attachmentUploads.value
    });

    if (createNewConvoTrpc.status.value === 'error') {
      actionLoading.value = false;
      toast.add({
        id: 'create_new_convo_fail',
        title: 'Conversation creation failed',
        description: `Conversation could not be created.`,
        color: 'red',
        icon: 'i-ph-warning-circle',
        timeout: 5000
      });
      return;
    }

    toast.add({
      title: 'Conversation created',
      description: `Redirecting to new conversation...`,
      icon: 'i-ph-thumbs-up',
      timeout: 5000
    });
    setTimeout(() => {
      navigateTo(`/${orgShortcode}/convo/${createNewConvo?.publicId}`);
    }, 1500);
  }
</script>
<template>
  <div class="flex h-full max-h-full w-full max-w-full flex-col gap-4 p-4">
    <div class="z-20000 from-base-1 mb-[-24px] h-[24px] bg-gradient-to-b" />
    <UnUiAlert
      v-if="
        orgEmailIdentities.length === 0 &&
        userEmailIdentitiesStatus === 'success'
      "
      icon="i-ph-warning-octagon"
      color="orange"
      description="You don't have an email identity assigned to you. Please contact your organization administrator."
      title="Email sending disabled!" />
    <div class="flex flex-col gap-2">
      <span class="text-sm font-medium">Participants</span>
      <div class="flex flex-col gap-1">
        <div class="flex flex-col gap-2">
          <div class="flex flex-row flex-wrap gap-4">
            <NuxtUiSelectMenu
              v-model="participantLabels"
              placeholder="Select participants"
              :options="
                participantOptions as Array<{
                  [key: string]: any;
                  disabled?: boolean;
                }>
              "
              name="name"
              searchable
              multiple
              :searchable-placeholder="participantPlaceholder"
              option-attribute="keywords"
              class="w-full"
              :creatable="orgEmailIdentities.length !== 0">
              <template
                v-if="selectedParticipants"
                #label>
                <!-- <UnUiIcon
                  name="i-ph-check"
                  class="h-4 w-4" /> -->
                <div
                  v-if="selectedParticipants.length"
                  class="flex flex-wrap gap-3">
                  <div
                    v-for="(participant, index) in selectedParticipants"
                    :key="index"
                    class="flex flex-row items-center gap-2 truncate">
                    <span
                      v-if="hasEmailParticipants && index === 0"
                      class="leading-0 text-base-11 text-xs">
                      TO:
                    </span>
                    <div
                      v-if="participant.type === 'email'"
                      class="flex flex-row items-center gap-1">
                      <UnUiIcon :name="participant.icon" />
                      <span>
                        {{ participant.address }}
                      </span>
                    </div>
                    <div
                      v-if="participant.type === 'contact'"
                      class="flex flex-row items-center gap-1">
                      <UnUiAvatar
                        :public-id="participant.publicId"
                        :avatar-timestamp="participant.avatarTimestamp"
                        :type="'contact'"
                        :alt="participant.name.toString()"
                        size="xs" />
                      <span>
                        {{ participant.name }}
                      </span>
                    </div>
                    <div
                      v-if="participant.type === 'orgMember'"
                      class="flex flex-row items-center gap-1">
                      <UnUiAvatar
                        :public-id="participant.profilePublicId"
                        :avatar-timestamp="participant.avatarTimestamp"
                        :type="'orgMember'"
                        :alt="participant.name.toString()"
                        size="xs" />
                      <span>
                        {{ participant.name }}
                      </span>
                    </div>
                    <div
                      v-if="participant.type === 'group'"
                      class="flex flex-row items-center gap-1">
                      <UnUiAvatar
                        :public-id="participant.publicId"
                        :avatar-timestamp="participant.avatarTimestamp"
                        :type="'group'"
                        :alt="participant.name.toString()"
                        :color="participant.color as UiColor"
                        size="xs" />
                      <span>
                        {{ participant.name }}
                      </span>
                    </div>
                    <span
                      v-if="
                        hasEmailParticipants &&
                        index === 0 &&
                        selectedParticipants.length > 1
                      "
                      class="border-l-1 border-l-1 leading-0 text-base-11 ml-2 border-l pl-2 text-xs">
                      CC:
                    </span>
                  </div>
                </div>
                <span v-else>{{ participantPlaceholder }}</span>
              </template>
              <template #option="{ option }">
                <UnUiIcon :name="option.icon" />
                <div v-if="option.type === 'email'">
                  <span> {{ option.address }} </span>
                </div>
                <div
                  v-if="option.type === 'contact'"
                  class="flex flex-row items-center gap-2">
                  <UnUiAvatar
                    :public-id="option.publicId"
                    :avatar-timestamp="option.avatarTimestamp"
                    :type="'contact'"
                    :alt="option.name"
                    size="xs" />
                  <span>
                    {{ option.name }}
                  </span>
                  <span class="text-xs"> - {{ option.address }}</span>
                </div>
                <div
                  v-if="option.type === 'orgMember'"
                  class="flex flex-row items-center gap-2">
                  <UnUiAvatar
                    :public-id="option.profilePublicId"
                    :avatar-timestamp="option.avatarTimestamp"
                    :type="'orgMember'"
                    :alt="option.name"
                    size="xs" />
                  <span>
                    {{ option.own ? 'You' : option.name }}
                    <span
                      v-if="option.title"
                      class="text-xs">
                      - {{ option.title }}
                    </span>
                    <span
                      v-if="option.disabled && !option.own"
                      class="text-xs">
                      - Cant be added
                    </span>
                    <span
                      v-if="option.disabled && option.own"
                      class="text-xs">
                      - already a participant
                    </span>
                  </span>
                </div>
                <div
                  v-if="option.type === 'group'"
                  class="flex flex-row items-center gap-2">
                  <UnUiAvatar
                    :public-id="option.publicId"
                    :avatar-timestamp="option.avatarTimestamp"
                    :type="'group'"
                    :alt="option.name"
                    :color="option.color.toString()"
                    size="xs" />
                  <span>
                    {{ option.name }}
                  </span>
                </div>
              </template>
              <template #option-create="{ option }">
                <span class="flex-shrink-0">New Email:</span>
                <span class="block truncate">{{ option.keywords }}</span>
              </template>
            </NuxtUiSelectMenu>
          </div>
        </div>
      </div>
    </div>
    <div
      v-show="hasEmailParticipants"
      class="flex flex-col gap-2 transition-all"
      :class="hasEmailParticipants ? 'opacity-100' : 'h-0 opacity-0'">
      <span class="text-sm font-medium"> Send External Email As </span>
      <div class="flex flex-col gap-4">
        <div class="flex flex-col gap-1">
          <div class="flex flex-row flex-wrap gap-8">
            <NuxtUiSelectMenu
              v-model="selectedOrgEmailIdentities"
              searchable
              :disabled="orgEmailIdentities.length === 0"
              :placeholder="orgEmailIdentitiesPlaceholder"
              :options="orgEmailIdentities"
              :ui="{
                wrapper: 'w-full',
                color: {
                  white: {
                    outline: emailButNoIdentityRingColor,
                    background: 'bg-base-1'
                  }
                }
              }">
              <template
                v-if="selectedOrgEmailIdentities"
                #label>
                <UnUiIcon
                  name="i-ph-check"
                  class="h-4 w-4" />
                <div
                  v-if="selectedOrgEmailIdentities"
                  class="flex flex-wrap gap-3">
                  <div class="flex flex-row items-center gap-1 truncate">
                    <span
                      >{{ selectedOrgEmailIdentities.sendName }}
                      <span class="text-base-11"
                        >- {{ selectedOrgEmailIdentities.address }}</span
                      >
                    </span>
                  </div>
                </div>
                <span v-else>Select email identity</span>
              </template>
              <template #option="{ option }">
                <span
                  >{{ option.sendName }}
                  <span class="text-base-11">- {{ option.address }}</span>
                </span>
              </template>
              <template #option-empty=""> No email identities found </template>
            </NuxtUiSelectMenu>
          </div>
        </div>
      </div>
    </div>
    <div class="flex w-full flex-col gap-2">
      <UnUiInput
        v-model:value="conversationTopicInput"
        v-model:valid="conversationSubjectInputValid"
        width="full"
        label="Topic"
        :schema="z.string().trim().min(1).max(128)" />
    </div>

    <div
      class="flex h-full max-h-full w-full flex-col justify-items-end gap-2 overflow-hidden">
      <span class="text-sm font-medium">Message</span>
      <UnEditor
        v-model:modelValue="messageEditorData"
        class="min-h-[150px] overflow-hidden" />
    </div>
    <div
      class="flex w-full max-w-full grow flex-row items-center justify-end gap-2">
      <div
        class="flex w-full max-w-full grow flex-row justify-end gap-2 overflow-scroll">
        <div
          v-for="attachment in attachmentUploads"
          :key="attachment.attachmentPublicId"
          class="w-fit">
          <UnUiTooltip text="click to remove">
            <div
              class="border-1 border-base-9 text-base-11 hover:border-red-9 hover:bg-base-12 hover:text-red-9 flex flex-row gap-1 rounded-md border px-2 py-1">
              <UnUiIcon name="i-ph-paperclip" />
              <span class="truncate text-xs"> {{ attachment.fileName }}</span>
            </div>
          </UnUiTooltip>
        </div>
      </div>
      <ConvosUpload
        v-model:uploadedAttachments="attachmentUploads"
        :max-size="15000000"
        :current-size="currentTotalUploadSize"
        :org-shortcode="orgShortcode">
        <template #default="{ openFileDialog, loading }">
          <UnUiButton
            label="Upload"
            variant="outline"
            :loading="loading"
            icon="i-ph-upload"
            @click="openFileDialog" />
        </template>
      </ConvosUpload>
      <UnUiButton
        label="Save Draft"
        color="amber"
        variant="outline"
        :disabled="!formValid || actionLoading"
        icon="i-ph-note" />
      <UnUiButton
        label="Post Comment"
        color="yellow"
        variant="outline"
        :disabled="!formValid || actionLoading"
        icon="i-ph-note"
        @click="createNewConvo('comment')" />
      <UnUiButton
        label="Send Message"
        variant="outline"
        :disabled="!formValid || actionLoading"
        icon="i-ph-envelope"
        @click="createNewConvo('message')" />
    </div>
  </div>
</template>

// apps/web/app/[orgShortCode]/convo/new/page.tsx
'use client';

import { api } from '@/lib/trpc';
import { cn, generateAvatarUrl, getInitials } from '@/lib/utils';
import {
  Avatar,
  Badge,
  Button,
  Flex,
  Heading,
  Popover,
  Select,
  Text,
  TextField
} from '@radix-ui/themes';
import { type TypeId } from '@u22n/utils';
import {
  Command,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
  CommandLoading,
  useCommandState
} from 'cmdk';
import { useState, useMemo, Fragment } from 'react';
import {
  type LucideIcon,
  UserIcon,
  UsersIcon,
  BookUserIcon,
  AtSignIcon,
  ChevronDown,
  Check
} from 'lucide-react';
import { z } from 'zod';
import {
  type JSONContent,
  emptyTiptapEditorContent
} from '@u22n/tiptap/react/components';
import Editor from './editor';
import { atom, useAtom, useAtomValue, useSetAtom } from 'jotai';
import useLoading from '@/hooks/use-loading';
import { stringify } from 'superjson';
import { toast } from 'sonner';
import { useRouter } from 'next/navigation';
import { useGlobalStore } from '@/providers/global-store-provider';
import AttachmentButton, {
  type ConvoAttachmentUpload
} from './attachment-button';

interface ConvoParticipantOrgMembers {
  type: 'orgMember';
  icon: LucideIcon;
  publicId: TypeId<'orgMembers'>;
  avatarTimestamp: Date | null;
  profilePublicId: TypeId<'orgMemberProfile'>;
  name: string;
  handle: string;
  title: string | null;
  disabled?: boolean;
  keywords: string[];
  own?: boolean;
}
interface ConvoParticipantOrgTeams {
  type: 'team';
  icon: LucideIcon;
  publicId: TypeId<'teams'>;
  avatarTimestamp: Date | null;
  name: string;
  description: string | null;
  color: string | null;
  keywords: string[];
}
interface ConvoParticipantOrgContacts {
  type: 'contact';
  icon: LucideIcon;
  publicId: TypeId<'contacts'>;
  avatarTimestamp: Date | null;
  name: string | null;
  address: string;
  keywords: string[];
  screenerStatus: 'pending' | 'approve' | 'reject' | null;
}
interface NewConvoParticipantEmailAddresses {
  type: 'email';
  icon: LucideIcon;
  publicId: string;
  address: string;
  keywords: string[];
}

type NewConvoParticipant =
  | ConvoParticipantOrgMembers
  | ConvoParticipantOrgTeams
  | ConvoParticipantOrgContacts
  | NewConvoParticipantEmailAddresses;

const selectedParticipantsAtom = atom<NewConvoParticipant[]>([]);
const newEmailParticipantsAtom = atom<string[]>([]);
const attachmentsAtom = atom<ConvoAttachmentUpload[]>([]);

export default function Page() {
  const orgShortCode = useGlobalStore((state) => state.currentOrg.shortCode);

  const { data: userEmailIdentities, isLoading: emailIdentitiesLoading } =
    api.org.mail.emailIdentities.getUserEmailIdentities.useQuery({
      orgShortCode
    });
  const { data: orgMemberList, isLoading: orgMemberListLoading } =
    api.org.users.members.getOrgMembersList.useQuery({ orgShortCode });
  const { data: orgTeamsData, isLoading: orgTeamsLoading } =
    api.org.users.teams.getOrgTeams.useQuery({ orgShortCode });
  const { data: orgContacts, isLoading: orgContactsLoading } =
    api.org.contacts.getOrgContacts.useQuery({ orgShortCode });
  const { mutateAsync: createConvoFn } =
    api.convos.createNewConvo.useMutation();

  const newEmailParticipants = useAtomValue(newEmailParticipantsAtom);
  const selectedParticipants = useAtomValue(selectedParticipantsAtom);
  const attachments = useAtomValue(attachmentsAtom);

  const router = useRouter();

  const [selectedEmailIdentity, setSelectedEmailIdentity] = useState<
    string | null
  >(null);
  const [topic, setTopic] = useState('');

  const allParticipantsLoaded = useMemo(
    () =>
      ![
        emailIdentitiesLoading,
        orgMemberListLoading,
        orgTeamsLoading,
        orgContactsLoading
      ].every((loading) => loading === false),
    [
      emailIdentitiesLoading,
      orgMemberListLoading,
      orgTeamsLoading,
      orgContactsLoading
    ]
  );

  const allParticipants = useMemo(() => {
    const participants: NewConvoParticipant[] = [];

    if (orgMemberList?.ownMembershipId) {
      const ownOrgMemberData = orgMemberList.members?.find(
        (member) => member.publicId === orgMemberList.ownMembershipId
      );
      if (!ownOrgMemberData) {
        throw new Error('own org member data not found');
      }
      const ownData: ConvoParticipantOrgMembers = {
        type: 'orgMember',
        icon: UserIcon,
        publicId: ownOrgMemberData.publicId,
        profilePublicId: ownOrgMemberData.profile.publicId,
        avatarTimestamp: ownOrgMemberData.profile.avatarTimestamp,
        name: `${ownOrgMemberData.profile?.firstName} ${ownOrgMemberData.profile?.lastName ?? ''}`,
        handle: ownOrgMemberData.profile?.handle ?? '',
        title: ownOrgMemberData.profile?.title ?? '',
        keywords: [
          ownOrgMemberData.profile?.firstName,
          ownOrgMemberData.profile?.lastName,
          `@${ownOrgMemberData.profile?.handle ?? ''}`,
          ownOrgMemberData.profile?.title
        ].filter(Boolean) as string[],
        disabled: true,
        own: true
      };
      participants.push(ownData);
    }

    if (orgMemberList?.members) {
      for (const member of orgMemberList.members) {
        if (member.publicId === orgMemberList.ownMembershipId) {
          continue;
        }
        participants.push({
          type: 'orgMember',
          icon: UserIcon,
          publicId: member.publicId,
          profilePublicId: member.profile.publicId,
          avatarTimestamp: member.profile.avatarTimestamp,
          name: `${member.profile?.firstName ?? ''} ${member.profile?.lastName ?? ''}`,
          handle: member.profile?.handle ?? '',
          title: member.profile?.title ?? '',
          keywords: [
            member.profile?.firstName,
            member.profile?.lastName,
            `@${member.profile?.handle ?? ''}`,
            member.profile?.title
          ].filter(Boolean) as string[]
        });
      }
    }

    if (orgTeamsData?.teams) {
      for (const team of orgTeamsData.teams) {
        participants.push({
          type: 'team',
          icon: UsersIcon,
          publicId: team.publicId,
          avatarTimestamp: team.avatarTimestamp,
          name: team.name,
          description: team.description,
          color: team.color,
          keywords: [team.name, team.description].filter(Boolean) as string[]
        });
      }
    }

    if (orgContacts?.contacts) {
      for (const contact of orgContacts.contacts) {
        participants.push({
          type: 'contact',
          icon: BookUserIcon,
          publicId: contact.publicId,
          avatarTimestamp: contact.avatarTimestamp,
          name: contact.setName ?? contact.name ?? null,
          address: `${contact.emailUsername}@${contact.emailDomain}`,
          keywords: [
            contact.setName,
            contact.name,
            `${contact.emailUsername}@${contact.emailDomain}`
          ].filter(Boolean) as string[],
          screenerStatus: contact.screenerStatus
        });
      }
    }

    if (newEmailParticipants.length > 0) {
      for (const emailParticipant of newEmailParticipants) {
        participants.push({
          type: 'email',
          icon: AtSignIcon,
          publicId: emailParticipant,
          address: emailParticipant,
          keywords: [emailParticipant]
        });
      }
    }
    return participants;
  }, [
    orgContacts?.contacts,
    orgMemberList?.members,
    orgMemberList?.ownMembershipId,
    orgTeamsData?.teams,
    newEmailParticipants
  ]);

  const [editorText, setEditorText] = useState<JSONContent>(
    emptyTiptapEditorContent
  );

  const isTextPresent = useMemo(() => {
    const contentArray = editorText?.content;
    if (!contentArray) return false;
    if (contentArray.length === 0) return false;
    if (
      contentArray[0] &&
      (!contentArray[0].content || contentArray[0].content.length === 0)
    )
      return false;
    return true;
  }, [editorText]);

  const isFormValid = useMemo(() => {
    if (
      isTextPresent &&
      topic.length > 0 &&
      selectedParticipants.length > 0 &&
      selectedEmailIdentity
    )
      return true;
    return false;
  }, [isTextPresent, topic, selectedParticipants, selectedEmailIdentity]);

  async function startConvoUnderlying(type: 'message' | 'comment') {
    const getPublicIdsByType = (
      type: NewConvoParticipant['type'],
      property = 'publicId'
    ) =>
      selectedParticipants
        .filter((participant) => participant.type === type)
        .map((participant) =>
          participant[property as keyof NewConvoParticipant].toString()
        );

    const participantsOrgMembersPublicIds = getPublicIdsByType('orgMember');
    const participantsTeamsPublicIds = getPublicIdsByType('team');
    const participantsContactsPublicIds = getPublicIdsByType('contact');
    const participantsEmails = getPublicIdsByType('email', 'address');

    const firstParticipant = selectedParticipants[0]!;
    const toParticipant:
      | { type: 'email'; emailAddress: string }
      | { type: 'orgMember' | 'team' | 'contact'; publicId: string } =
      firstParticipant.type === 'email'
        ? {
            type: 'email',
            emailAddress: firstParticipant.publicId
          }
        : {
            type: firstParticipant.type,
            publicId: firstParticipant.publicId
          };

    return await createConvoFn({
      firstMessageType: type,
      topic,
      to: toParticipant,
      sendAsEmailIdentityPublicId: selectedEmailIdentity!,
      participantsOrgMembersPublicIds,
      participantsTeamsPublicIds,
      participantsContactsPublicIds,
      participantsEmails,
      message: stringify(editorText),
      attachments,
      orgShortCode
    });
  }

  const { loading: isMessageLoading, run: createConvo } = useLoading(
    async () => await startConvoUnderlying('message'),
    {
      onError: (err) => {
        toast.error(err.message);
      },
      onSuccess: (data) => {
        toast.success('Convo created, redirecting you to your conversion');
        router.push(`/${orgShortCode}/convo/${data.publicId}`);
      }
    }
  );

  const { loading: isCommentLoading, run: createComment } = useLoading(
    async () => await startConvoUnderlying('comment'),
    {
      onError: (err) => {
        toast.error(err.message);
      },
      onSuccess: (data) => {
        toast.success('Convo created, redirecting you to your conversion');
        router.push(`/${orgShortCode}/convo/${data.publicId}`);
      }
    }
  );

  return (
    <Flex
      direction="column"
      gap="3"
      className="w-full p-3">
      <Flex
        direction="column"
        gap="2"
        className="w-full">
        <Heading size="2">Participants</Heading>
        <ParticipantsComboboxPopover
          participants={allParticipants}
          loading={allParticipantsLoaded}
        />
      </Flex>
      <Flex
        direction="column"
        gap="2"
        className="w-full">
        <Heading size="2">Email Identity</Heading>
        <Select.Root
          onValueChange={(value) => {
            setSelectedEmailIdentity(value);
          }}>
          <Select.Trigger placeholder="Select an Email Identity to Use" />
          <Select.Content>
            {userEmailIdentities?.emailIdentities.map((identity) => (
              <Select.Item
                key={identity.publicId}
                value={identity.publicId}>
                {identity.sendName} ({identity.username}@{identity.domainName})
              </Select.Item>
            ))}
          </Select.Content>
        </Select.Root>
      </Flex>
      <Flex
        className="w-full"
        direction="column"
        gap="2">
        <Heading size="2">Subject</Heading>
        <TextField.Root
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          placeholder="Type a Subject"
          className="w-full"
        />
      </Flex>
      <Flex
        className="w-full flex-1"
        direction="column"
        gap="2">
        <Heading size="2">Type Your Message</Heading>
        <Flex className="flex-1">
          <Editor
            initialValue={editorText}
            onChange={setEditorText}
          />
        </Flex>
      </Flex>
      <Flex
        justify="end"
        gap="2">
        <AttachmentButton attachmentsAtom={attachmentsAtom} />
        <Button
          variant="soft"
          loading={isCommentLoading}
          disabled={!isFormValid || isMessageLoading}
          onClick={() => createComment()}>
          Comment
        </Button>
        <Button
          loading={isMessageLoading}
          disabled={!isFormValid || isCommentLoading}
          onClick={() => createConvo()}>
          Send
        </Button>
      </Flex>
    </Flex>
  );
}

type ParticipantsComboboxPopoverProps = {
  participants: NewConvoParticipant[];
  loading: boolean;
};

function ParticipantsComboboxPopover({
  participants,
  loading
}: ParticipantsComboboxPopoverProps) {
  const [open, setOpen] = useState(false);
  const [selectedParticipants, setSelectedParticipants] = useAtom(
    selectedParticipantsAtom
  );

  const [currentSelectValue, setCurrentSelectValue] = useState('');
  const hasExternalParticipants = useMemo(
    () =>
      selectedParticipants.some(
        (participant) =>
          participant.type === 'email' || participant.type === 'contact'
      ),
    [selectedParticipants]
  );

  return (
    <div className="flex w-full items-center space-x-4">
      <Popover.Root
        open={open}
        onOpenChange={setOpen}>
        <Popover.Trigger>
          <Button
            variant="surface"
            className="h-fit w-full justify-between px-2 py-1">
            {selectedParticipants.length > 0 ? (
              <Flex
                gap="2"
                wrap="wrap">
                {selectedParticipants.map((participant, i) => {
                  let info = '';
                  switch (participant.type) {
                    case 'orgMember':
                      info = participant.name;
                      break;
                    case 'team':
                      info = participant.name;
                      break;
                    case 'contact':
                      info = participant.name
                        ? `${participant.name} (${participant.address})`
                        : participant.address;
                      break;
                    case 'email':
                      info = participant.address;
                      break;
                  }
                  return (
                    <Fragment key={participant.publicId}>
                      <Badge
                        color={i === 0 ? undefined : 'gray'}
                        variant="surface"
                        className="">
                        <Avatar
                          src={
                            participant.type === 'email'
                              ? undefined
                              : generateAvatarUrl({
                                  publicId:
                                    participant.type === 'orgMember'
                                      ? participant.profilePublicId
                                      : participant.publicId,
                                  avatarTimestamp: participant.avatarTimestamp,
                                  size: 'sm'
                                }) ?? undefined
                          }
                          fallback={getInitials(info.replace(/\(.+\)/, ''))}
                          size="1"
                          className="rounded-full"
                        />
                        <Text>{info}</Text>
                      </Badge>
                      {i === 0 &&
                        selectedParticipants.length > 1 &&
                        hasExternalParticipants && (
                          <div className="border-gray-10 dark:border-graydark-10 my-1 flex h-full items-center justify-center border-l-2 px-1">
                            CC:
                          </div>
                        )}
                    </Fragment>
                  );
                })}
              </Flex>
            ) : (
              <>
                <Text>Search or type an Email address</Text>
                <ChevronDown size={16} />
              </>
            )}
          </Button>
        </Popover.Trigger>
        <Popover.Content
          className="p-2"
          side="bottom"
          align="start">
          <Command
            value={currentSelectValue}
            onValueChange={(value) => setCurrentSelectValue(value)}
            className="flex flex-col gap-3"
            filter={(value, search, keywords) =>
              (
                keywords?.join(' ').toLowerCase() ?? value.toLowerCase()
              ).includes(search.toLowerCase())
                ? 1
                : 0
            }>
            <CommandInput asChild>
              <TextField.Root
                placeholder="Search or type an Email address"
                onKeyDown={(e) => {
                  // Hack to prevent cmdk from preventing Home and End keys
                  if (e.key === 'Home' || e.key === 'End') {
                    e.stopPropagation();
                  }
                }}
                onFocus={() => {
                  // Remove current select value when input is focused
                  setCurrentSelectValue('');
                }}
              />
            </CommandInput>
            <CommandList>
              {loading && <CommandLoading>Loading Participants</CommandLoading>}

              <CommandGroup className="flex flex-col gap-2 px-1">
                {!loading && <EmptyStateHandler />}
                {participants.map((participant) => (
                  <CommandItem
                    key={participant.publicId}
                    value={participant.publicId}
                    keywords={participant.keywords}
                    onSelect={(value) => {
                      setSelectedParticipants((prev) =>
                        prev.find((p) => p.publicId === value)
                          ? prev.filter((p) => p.publicId !== value)
                          : prev.concat(participant)
                      );
                    }}>
                    <Button
                      variant="ghost"
                      className="my-1 w-full justify-start px-1"
                      color={
                        selectedParticipants.find(
                          (p) => p.publicId === participant.publicId
                        )
                          ? undefined
                          : 'gray'
                      }
                      disabled={
                        participant.type === 'orgMember' && participant.disabled
                      }
                      onFocus={() =>
                        setCurrentSelectValue(participant.publicId)
                      }>
                      <participant.icon className={cn('mr-2 h-4 w-4')} />
                      {participant.type === 'orgMember' ? (
                        <Flex
                          gap="2"
                          align="center"
                          justify="center">
                          <Avatar
                            src={
                              generateAvatarUrl({
                                publicId: participant.profilePublicId,
                                avatarTimestamp: participant.avatarTimestamp,
                                size: 'sm'
                              }) ?? undefined
                            }
                            fallback={getInitials(participant.name)}
                            size="1"
                            className="rounded-full"
                          />
                          <Text size="2">
                            {participant.own
                              ? 'You (already a participant)'
                              : `${participant.name} ${participant.title ? `(${participant.title})` : ''}`}
                          </Text>
                        </Flex>
                      ) : participant.type === 'team' ? (
                        <Flex
                          gap="2"
                          align="center"
                          justify="center">
                          <Avatar
                            src={
                              generateAvatarUrl({
                                publicId: participant.publicId,
                                avatarTimestamp: participant.avatarTimestamp,
                                size: 'sm'
                              }) ?? undefined
                            }
                            fallback={getInitials(participant.name)}
                            size="1"
                            className="rounded-full"
                          />
                          <Text size="2">{participant.name}</Text>
                        </Flex>
                      ) : participant.type === 'contact' ? (
                        <Flex
                          gap="2"
                          align="center"
                          justify="center">
                          <Avatar
                            src={
                              generateAvatarUrl({
                                publicId: participant.publicId,
                                avatarTimestamp: participant.avatarTimestamp,
                                size: 'sm'
                              }) ?? undefined
                            }
                            fallback={getInitials(
                              participant.name ?? participant.address
                            )}
                            size="1"
                            className="rounded-full"
                          />
                          <Text size="2">
                            {participant.name} {participant.name && '-'}{' '}
                            {participant.address}
                          </Text>
                        </Flex>
                      ) : (
                        <Flex
                          gap="2"
                          align="center"
                          justify="center">
                          <Avatar
                            fallback={getInitials(participant.address)}
                            size="1"
                            className="rounded-full"
                          />
                          <Text size="2">{participant.address}</Text>
                        </Flex>
                      )}
                      {selectedParticipants.find(
                        (p) => p.publicId === participant.publicId
                      ) ? (
                        <Check size={16} />
                      ) : null}
                    </Button>
                  </CommandItem>
                ))}
              </CommandGroup>
            </CommandList>
          </Command>
        </Popover.Content>
      </Popover.Root>
    </div>
  );
}

function EmptyStateHandler() {
  const isEmpty = useCommandState((state) => state.filtered.count === 0);
  const email = useCommandState((state) => state.search);
  const isValidEmail = useMemo(
    () => z.string().email().safeParse(email).success,
    [email]
  );

  const setEmailParticipants = useSetAtom(newEmailParticipantsAtom);
  const addSelectedParticipant = useSetAtom(selectedParticipantsAtom);

  const addEmailParticipant = (email: string) => {
    setEmailParticipants((prev) =>
      prev.includes(email) ? prev : prev.concat(email)
    );
    addSelectedParticipant((prev) =>
      prev.find((p) => p.publicId === email)
        ? prev
        : prev.concat({
            type: 'email',
            icon: AtSignIcon,
            publicId: email,
            address: email,
            keywords: [email]
          })
    );
  };

  return isEmpty && isValidEmail ? (
    <CommandItem
      key={email}
      value={email}
      forceMount
      onKeyDown={(e) => {
        // Submit email on Enter key
        if (e.key === 'Enter') {
          addEmailParticipant(email);
        }
      }}>
      <Button
        variant="ghost"
        className="my-1 w-full justify-start px-1"
        color="gray"
        onClick={() => {
          addEmailParticipant(email);
        }}>
        <AtSignIcon className="mr-2 h-4 w-4" />
        <Text size="2">Add {email}</Text>
      </Button>
    </CommandItem>
  ) : (
    <CommandEmpty className="px-2 text-sm font-bold">
      No participants found. Try typing an email address.
    </CommandEmpty>
  );
}
